routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('users', 'UserController');

Route::resource('userLocations', 'UserLocationController');

Route::resource('wallets', 'WalletController');

Route::resource('locations', 'LocationController');

Route::resource('typeTransactionCategories', 'TypeTransactionCategoryController');

Route::resource('transactionCategories', 'TransactionCategoryController');

Route::resource('budgets', 'BudgetController');

Route::resource('transactions', 'TransactionController');

Route::resource('periods', 'PeriodController');

Route::resource('userConnexions', 'UserConnexionController');

app/Models/UserLocation.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="UserLocation",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="client_id",
 *          description="client_id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="user_id",
 *          description="user_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="location_id",
 *          description="location_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class UserLocation extends Model
{
    use SoftDeletes;

    public $table = 'user_locations';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'client_id',
        'user_id',
        'location_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'client_id' => 'string',
        'user_id' => 'integer',
        'location_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/UserLocationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserLocationRequest;
use App\Http\Requests\UpdateUserLocationRequest;
use App\Repositories\UserLocationRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class UserLocationController extends AppBaseController
{
    /** @var  UserLocationRepository */
    private $userLocationRepository;

    public function __construct(UserLocationRepository $userLocationRepo)
    {
        $this->userLocationRepository = $userLocationRepo;
    }

    /**
     * Display a listing of the UserLocation.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->userLocationRepository->pushCriteria(new RequestCriteria($request));
        $userLocations = $this->userLocationRepository->all();

        return view('user_locations.index')
            ->with('userLocations', $userLocations);
    }

    /**
     * Show the form for creating a new UserLocation.
     *
     * @return Response
     */
    public function create()
    {
        return view('user_locations.create');
    }

    /**
     * Store a newly created UserLocation in storage.
     *
     * @param CreateUserLocationRequest $request
     *
     * @return Response
     */
    public function store(CreateUserLocationRequest $request)
    {
        $input = $request->all();

        $userLocation = $this->userLocationRepository->create($input);

        Flash::success('User Location saved successfully.');

        return redirect(route('userLocations.index'));
    }

    /**
     * Display the specified UserLocation.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $userLocation = $this->userLocationRepository->findWithoutFail($id);

        if (empty($userLocation)) {
            Flash::error('User Location not found');

            return redirect(route('userLocations.index'));
        }

        return view('user_locations.show')->with('userLocation', $userLocation);
    }

    /**
     * Show the form for editing the specified UserLocation.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $userLocation = $this->userLocationRepository->findWithoutFail($id);

        if (empty($userLocation)) {
            Flash::error('User Location not found');

            return redirect(route('userLocations.index'));
        }

        return view('user_locations.edit')->with('userLocation', $userLocation);
    }

    /**
     * Update the specified UserLocation in storage.
     *
     * @param  int              $id
     * @param UpdateUserLocationRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUserLocationRequest $request)
    {
        $userLocation = $this->userLocationRepository->findWithoutFail($id);

        if (empty($userLocation)) {
            Flash::error('User Location not found');

            return redirect(route('userLocations.index'));
        }

        $userLocation = $this->userLocationRepository->update($request->all(), $id);

        Flash::success('User Location updated successfully.');

        return redirect(route('userLocations.index'));
    }

    /**
     * Remove the specified UserLocation from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $userLocation = $this->userLocationRepository->findWithoutFail($id);

        if (empty($userLocation)) {
            Flash::error('User Location not found');

            return redirect(route('userLocations.index'));
        }

        $this->userLocationRepository->delete($id);

        Flash::success('User Location deleted successfully.');

        return redirect(route('userLocations.index'));
    }
}

resources/views/user_locations/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Location
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'userLocations.store']) !!}

                        @include('user_locations.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user_locations/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Location
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($userLocation, ['route' => ['userLocations.update', $userLocation->id], 'method' => 'patch']) !!}

                        @include('user_locations.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/user_locations/fields.blade.php
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('userLocations.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/user_locations/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">User Locations</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('userLocations.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('user_locations.table')
            </div>
        </div>
    </div>
@endsection

resources/views/user_locations/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Location
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('user_locations.show_fields')
                    <a href="{!! route('userLocations.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user_locations/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $userLocation->id !!}</p>
</div>

<!-- Client Id Field -->
<div class="form-group">
    {!! Form::label('client_id', 'Client Id:') !!}
    <p>{!! $userLocation->client_id !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{!! $userLocation->user_id !!}</p>
</div>

<!-- Location Id Field -->
<div class="form-group">
    {!! Form::label('location_id', 'Location Id:') !!}
    <p>{!! $userLocation->location_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $userLocation->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $userLocation->updated_at !!}</p>
</div>

resources/views/user_locations/table.blade.php
<table class="table table-responsive" id="userLocations-table">
    <thead>
        <tr>
            <th>Client Id</th>
        <th>User Id</th>
        <th>Location Id</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($userLocations as $userLocation)
        <tr>
            <td>{!! $userLocation->client_id !!}</td>
            <td>{!! $userLocation->user_id !!}</td>
            <td>{!! $userLocation->location_id !!}</td>
            <td>
                {!! Form::open(['route' => ['userLocations.destroy', $userLocation->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('userLocations.show', [$userLocation->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('userLocations.edit', [$userLocation->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>