routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('users', 'UserController');

Route::resource('userLocations', 'UserLocationController');

Route::resource('wallets', 'WalletController');

Route::resource('locations', 'LocationController');

Route::resource('typeTransactionCategories', 'TypeTransactionCategoryController');

Route::resource('transactionCategories', 'TransactionCategoryController');

Route::resource('budgets', 'BudgetController');

Route::resource('transactions', 'TransactionController');

Route::resource('periods', 'PeriodController');

Route::resource('userConnexions', 'UserConnexionController');

app/Models/UserConnexion.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="UserConnexion",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="device_model",
 *          description="device_model",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_manufacturer",
 *          description="device_manufacturer",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_product",
 *          description="device_product",
 *          type="string"
 *      ), 
 *      @SWG\Property(
 *          property="device_os_id",
 *          description="device_os_id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_os_version_id",
 *          description="device_os_version_id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_os_version_name",
 *          description="device_os_version_name",
 *          type="string"
 *      ), 
 *      @SWG\Property(
 *          property="device_id",
 *          description="device_id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_info",
 *          description="device_info",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="application_name",
 *          description="application_name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="application_version_name",
 *          description="application_version_name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="application_version_code",
 *          description="application_version_code",
 *          type="string"
 *      ), 
 *      @SWG\Property(
 *          property="screen_width",
 *          description="screen_width",
 *          type="string"
 *      ), 
 *      @SWG\Property(
 *          property="screen_height",
 *          description="screen_height",
 *          type="string"
 *      ), 
 *      @SWG\Property(
 *          property="screen_density",
 *          description="screen_density",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="screen_density_name",
 *          description="screen_density_name",
 *          type="string"
 *      ),    
 *      @SWG\Property(
 *          property="network",
 *          description="network",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="latitude",
 *          description="latitude",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="longitude",
 *          description="longitude",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="success",
 *          description="success",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class UserConnexion extends Model
{
    use SoftDeletes;

    public $table = 'user_connexions';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'device_model',
        'device_manufacturer',
        'device_product',
        'device_os_id',
        'device_os_version_id',
        'device_os_version_name',
        'device_id',
        'device_info',
        'application_name',
        'application_version_name',
        'application_version_code',
        'screen_width',
        'screen_height',
        'screen_density',
        'screen_density_name',
        'network',
        'latitude',
        'longitude',
        'success'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [  
        'device_model' => 'string',
        'device_manufacturer' => 'string',
        'device_product' => 'string',
        'device_os_id' => 'string',
        'device_os_version_id' => 'string',
        'device_os_version_name' => 'string',
        'device_id' => 'string',
        'device_info' => 'string',
        'application_name' => 'string',
        'application_version_name' => 'string',
        'application_version_code' => 'string',
        'screen_width' => 'string',
        'screen_height' => 'string',
        'screen_density' => 'string',
        'screen_density_name' => 'string',
        'network' => 'string',
        'latitude' => 'string',
        'longitude' => 'string',
        'success' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/UserConnexionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserConnexionRequest;
use App\Http\Requests\UpdateUserConnexionRequest;
use App\Repositories\UserConnexionRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class UserConnexionController extends AppBaseController
{
    /** @var  UserConnexionRepository */
    private $userConnexionRepository;

    public function __construct(UserConnexionRepository $userConnexionRepo)
    {
        $this->userConnexionRepository = $userConnexionRepo;
    }

    /**
     * Display a listing of the UserConnexion.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->userConnexionRepository->pushCriteria(new RequestCriteria($request));
        $userConnexions = $this->userConnexionRepository->all();

        return view('user_connexions.index')
            ->with('userConnexions', $userConnexions);
    }

    /**
     * Show the form for creating a new UserConnexion.
     *
     * @return Response
     */
    public function create()
    {
        return view('user_connexions.create');
    }

    /**
     * Store a newly created UserConnexion in storage.
     *
     * @param CreateUserConnexionRequest $request
     *
     * @return Response
     */
    public function store(CreateUserConnexionRequest $request)
    {
        $input = $request->all();

        $userConnexion = $this->userConnexionRepository->create($input);

        Flash::success('User Connexion saved successfully.');

        return redirect(route('userConnexions.index'));
    }

    /**
     * Display the specified UserConnexion.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $userConnexion = $this->userConnexionRepository->findWithoutFail($id);

        if (empty($userConnexion)) {
            Flash::error('User Connexion not found');

            return redirect(route('userConnexions.index'));
        }

        return view('user_connexions.show')->with('userConnexion', $userConnexion);
    }

    /**
     * Show the form for editing the specified UserConnexion.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $userConnexion = $this->userConnexionRepository->findWithoutFail($id);

        if (empty($userConnexion)) {
            Flash::error('User Connexion not found');

            return redirect(route('userConnexions.index'));
        }

        return view('user_connexions.edit')->with('userConnexion', $userConnexion);
    }

    /**
     * Update the specified UserConnexion in storage.
     *
     * @param  int              $id
     * @param UpdateUserConnexionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUserConnexionRequest $request)
    {
        $userConnexion = $this->userConnexionRepository->findWithoutFail($id);

        if (empty($userConnexion)) {
            Flash::error('User Connexion not found');

            return redirect(route('userConnexions.index'));
        }

        $userConnexion = $this->userConnexionRepository->update($request->all(), $id);

        Flash::success('User Connexion updated successfully.');

        return redirect(route('userConnexions.index'));
    }

    /**
     * Remove the specified UserConnexion from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $userConnexion = $this->userConnexionRepository->findWithoutFail($id);

        if (empty($userConnexion)) {
            Flash::error('User Connexion not found');

            return redirect(route('userConnexions.index'));
        }

        $this->userConnexionRepository->delete($id);

        Flash::success('User Connexion deleted successfully.');

        return redirect(route('userConnexions.index'));
    }
}

resources/views/user_connexions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Connexion
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'userConnexions.store']) !!}

                        @include('user_connexions.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user_connexions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Connexion
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($userConnexion, ['route' => ['userConnexions.update', $userConnexion->id], 'method' => 'patch']) !!}

                        @include('user_connexions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/user_connexions/fields.blade.php
<!-- Device Model Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_model', 'Device Model:') !!}
    {!! Form::text('device_model', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Os Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_os', 'Device Os:') !!}
    {!! Form::text('device_os', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_id', 'Device Id:') !!}
    {!! Form::text('device_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Info Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_info', 'Device Info:') !!}
    {!! Form::text('device_info', null, ['class' => 'form-control']) !!}
</div>

<!-- Network Field -->
<div class="form-group col-sm-6">
    {!! Form::label('network', 'Network:') !!}
    {!! Form::text('network', null, ['class' => 'form-control']) !!}
</div>

<!-- Latitude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('latitude', 'Latitude:') !!}
    {!! Form::text('latitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Longitude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('longitude', 'Longitude:') !!}
    {!! Form::text('longitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Success Field -->
<div class="form-group col-sm-6">
    {!! Form::label('success', 'Success:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('success', false) !!}
        {!! Form::checkbox('success', '1', null) !!} 1
    </label>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('userConnexions.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/user_connexions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">User Connexions</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('userConnexions.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('user_connexions.table')
            </div>
        </div>
    </div>
@endsection

resources/views/user_connexions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User Connexion
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('user_connexions.show_fields')
                    <a href="{!! route('userConnexions.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user_connexions/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $userConnexion->id !!}</p>
</div>

<!-- Device Model Field -->
<div class="form-group">
    {!! Form::label('device_model', 'Device Model:') !!}
    <p>{!! $userConnexion->device_model !!}</p>
</div>

<!-- Device Os Field -->
<div class="form-group">
    {!! Form::label('device_os', 'Device Os:') !!}
    <p>{!! $userConnexion->device_os !!}</p>
</div>

<!-- Device Id Field -->
<div class="form-group">
    {!! Form::label('device_id', 'Device Id:') !!}
    <p>{!! $userConnexion->device_id !!}</p>
</div>

<!-- Device Info Field -->
<div class="form-group">
    {!! Form::label('device_info', 'Device Info:') !!}
    <p>{!! $userConnexion->device_info !!}</p>
</div>

<!-- Network Field -->
<div class="form-group">
    {!! Form::label('network', 'Network:') !!}
    <p>{!! $userConnexion->network !!}</p>
</div>

<!-- Latitude Field -->
<div class="form-group">
    {!! Form::label('latitude', 'Latitude:') !!}
    <p>{!! $userConnexion->latitude !!}</p>
</div>

<!-- Longitude Field -->
<div class="form-group">
    {!! Form::label('longitude', 'Longitude:') !!}
    <p>{!! $userConnexion->longitude !!}</p>
</div>

<!-- Success Field -->
<div class="form-group">
    {!! Form::label('success', 'Success:') !!}
    <p>{!! $userConnexion->success !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $userConnexion->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $userConnexion->updated_at !!}</p>
</div>

resources/views/user_connexions/table.blade.php
<table class="table table-responsive" id="userConnexions-table">
    <thead>
        <tr>
            <th>Device Model</th>
        <th>Device Os</th>
        <th>Device Id</th>
        <th>Device Info</th>
        <th>Network</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Success</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($userConnexions as $userConnexion)
        <tr>
            <td>{!! $userConnexion->device_model !!}</td>
            <td>{!! $userConnexion->device_os !!}</td>
            <td>{!! $userConnexion->device_id !!}</td>
            <td>{!! $userConnexion->device_info !!}</td>
            <td>{!! $userConnexion->network !!}</td>
            <td>{!! $userConnexion->latitude !!}</td>
            <td>{!! $userConnexion->longitude !!}</td>
            <td>{!! $userConnexion->success !!}</td>
            <td>
                {!! Form::open(['route' => ['userConnexions.destroy', $userConnexion->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('userConnexions.show', [$userConnexion->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('userConnexions.edit', [$userConnexion->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>