routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('users', 'UserController');

Route::resource('userLocations', 'UserLocationController');

Route::resource('wallets', 'WalletController');

Route::resource('locations', 'LocationController');

Route::resource('typeTransactionCategories', 'TypeTransactionCategoryController');

Route::resource('transactionCategories', 'TransactionCategoryController');

Route::resource('budgets', 'BudgetController');

Route::resource('transactions', 'TransactionController');

Route::resource('periods', 'PeriodController');

Route::resource('userConnexions', 'UserConnexionController');

app/Models/TypeTransactionCategory.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="TypeTransactionCategory",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class TypeTransactionCategory extends Model
{
    use SoftDeletes;

    public $table = 'type_transaction_categories';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'name'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/TypeTransactionCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTypeTransactionCategoryRequest;
use App\Http\Requests\UpdateTypeTransactionCategoryRequest;
use App\Repositories\TypeTransactionCategoryRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class TypeTransactionCategoryController extends AppBaseController
{
    /** @var  TypeTransactionCategoryRepository */
    private $typeTransactionCategoryRepository;

    public function __construct(TypeTransactionCategoryRepository $typeTransactionCategoryRepo)
    {
        $this->typeTransactionCategoryRepository = $typeTransactionCategoryRepo;
    }

    /**
     * Display a listing of the TypeTransactionCategory.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->typeTransactionCategoryRepository->pushCriteria(new RequestCriteria($request));
        $typeTransactionCategories = $this->typeTransactionCategoryRepository->all();

        return view('type_transaction_categories.index')
            ->with('typeTransactionCategories', $typeTransactionCategories);
    }

    /**
     * Show the form for creating a new TypeTransactionCategory.
     *
     * @return Response
     */
    public function create()
    {
        return view('type_transaction_categories.create');
    }

    /**
     * Store a newly created TypeTransactionCategory in storage.
     *
     * @param CreateTypeTransactionCategoryRequest $request
     *
     * @return Response
     */
    public function store(CreateTypeTransactionCategoryRequest $request)
    {
        $input = $request->all();

        $typeTransactionCategory = $this->typeTransactionCategoryRepository->create($input);

        Flash::success('Type Transaction Category saved successfully.');

        return redirect(route('typeTransactionCategories.index'));
    }

    /**
     * Display the specified TypeTransactionCategory.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $typeTransactionCategory = $this->typeTransactionCategoryRepository->findWithoutFail($id);

        if (empty($typeTransactionCategory)) {
            Flash::error('Type Transaction Category not found');

            return redirect(route('typeTransactionCategories.index'));
        }

        return view('type_transaction_categories.show')->with('typeTransactionCategory', $typeTransactionCategory);
    }

    /**
     * Show the form for editing the specified TypeTransactionCategory.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $typeTransactionCategory = $this->typeTransactionCategoryRepository->findWithoutFail($id);

        if (empty($typeTransactionCategory)) {
            Flash::error('Type Transaction Category not found');

            return redirect(route('typeTransactionCategories.index'));
        }

        return view('type_transaction_categories.edit')->with('typeTransactionCategory', $typeTransactionCategory);
    }

    /**
     * Update the specified TypeTransactionCategory in storage.
     *
     * @param  int              $id
     * @param UpdateTypeTransactionCategoryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTypeTransactionCategoryRequest $request)
    {
        $typeTransactionCategory = $this->typeTransactionCategoryRepository->findWithoutFail($id);

        if (empty($typeTransactionCategory)) {
            Flash::error('Type Transaction Category not found');

            return redirect(route('typeTransactionCategories.index'));
        }

        $typeTransactionCategory = $this->typeTransactionCategoryRepository->update($request->all(), $id);

        Flash::success('Type Transaction Category updated successfully.');

        return redirect(route('typeTransactionCategories.index'));
    }

    /**
     * Remove the specified TypeTransactionCategory from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $typeTransactionCategory = $this->typeTransactionCategoryRepository->findWithoutFail($id);

        if (empty($typeTransactionCategory)) {
            Flash::error('Type Transaction Category not found');

            return redirect(route('typeTransactionCategories.index'));
        }

        $this->typeTransactionCategoryRepository->delete($id);

        Flash::success('Type Transaction Category deleted successfully.');

        return redirect(route('typeTransactionCategories.index'));
    }
}

resources/views/type_transaction_categories/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Transaction Category
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'typeTransactionCategories.store']) !!}

                        @include('type_transaction_categories.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/type_transaction_categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Transaction Category
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($typeTransactionCategory, ['route' => ['typeTransactionCategories.update', $typeTransactionCategory->id], 'method' => 'patch']) !!}

                        @include('type_transaction_categories.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/type_transaction_categories/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('typeTransactionCategories.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/type_transaction_categories/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Type Transaction Categories</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('typeTransactionCategories.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('type_transaction_categories.table')
            </div>
        </div>
    </div>
@endsection

resources/views/type_transaction_categories/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Transaction Category
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('type_transaction_categories.show_fields')
                    <a href="{!! route('typeTransactionCategories.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/type_transaction_categories/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $typeTransactionCategory->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $typeTransactionCategory->name !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $typeTransactionCategory->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $typeTransactionCategory->updated_at !!}</p>
</div>

resources/views/type_transaction_categories/table.blade.php
<table class="table table-responsive" id="typeTransactionCategories-table">
    <thead>
        <tr>
            <th>Name</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($typeTransactionCategories as $typeTransactionCategory)
        <tr>
            <td>{!! $typeTransactionCategory->name !!}</td>
            <td>
                {!! Form::open(['route' => ['typeTransactionCategories.destroy', $typeTransactionCategory->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('typeTransactionCategories.show', [$typeTransactionCategory->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('typeTransactionCategories.edit', [$typeTransactionCategory->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>